type UserActivity @entity(immutable: false) {
	id: ID!
	user: Bytes!
	accountSource: Bytes
	timestamp: BigInt!
	updateTimestamp: BigInt
}

type BalanceChange @entity(immutable: true) {
	id: ID!
	source: Bytes!
	type: String!
	account: Bytes!
	sideAccount: Bytes
	amount: BigInt!
	collateral: Bytes!
	timestamp: BigInt!
	blockNumber: BigInt!
	transaction: Bytes!
}

type QuoteEvent @entity(immutable: true) {
	id: ID!
	source: Bytes!
	quoteId: BigInt!
	quote: Quote!
	type: String!
	metadata: String
	timestamp: BigInt!
	blockNumber: BigInt!
	transaction: Bytes!
}

type DailyHistory @entity(immutable: false) {
	id: ID!
	source: Bytes!
	day: BigInt!
	quotesCount: BigInt!
	tradeVolume: BigInt!
	openTradeVolume: BigInt!
	closeTradeVolume: BigInt!
	liquidateTradeVolume: BigInt!
	deposit: BigInt!
	withdraw: BigInt!
	allocate: BigInt!
	deallocate: BigInt!
	activeUsers: BigInt!
	newUsers: BigInt!
	newAccounts: BigInt!
	platformFee: BigInt!
	openFee: BigInt!
	closeFee: BigInt!
	symmioShare: BigInt!
	openInterest: BigInt!
	fundingPaid: BigInt!
	fundingReceived: BigInt!
	averagePositionSize: BigInt!
	positionsCount: BigInt!
	accountSource: Bytes
	updateTimestamp: BigInt!
	timestamp: BigInt!
}

type AffiliateFeeCollector @entity(immutable: false) {
    id: ID!  # affiliate
    feeCollector: Bytes!
}

type FeeCollectorShare @entity(immutable: false) {
    id: ID!  # feeCollector
    symmioShare: BigInt
}

type SolverDailyHistory @entity(immutable: false) {
	id: ID!
	source: Bytes!
	day: BigInt!
	tradeVolume: BigInt!
	openTradeVolume: BigInt!
	closeTradeVolume: BigInt!
	liquidateTradeVolume: BigInt!
	openInterest: BigInt!
	averagePositionSize: BigInt!
	positionsCount: BigInt!
	fundingPaid: BigInt!
	fundingReceived: BigInt!
	solver: Bytes!
	accountSource: Bytes
	platformFee: BigInt!
	openFee: BigInt!
	closeFee: BigInt!
	updateTimestamp: BigInt!
	timestamp: BigInt!
}

type SolverOnlyDailyHistory @entity(immutable: false) {
	id: ID!
	source: Bytes!
	day: BigInt!
	tradeVolume: BigInt!
	openTradeVolume: BigInt!
	closeTradeVolume: BigInt!
	liquidateTradeVolume: BigInt!
	openInterest: BigInt!
	averagePositionSize: BigInt!
	positionsCount: BigInt!
	fundingPaid: BigInt!
	fundingReceived: BigInt!
	solver: Bytes!
	platformFee: BigInt!
	openFee: BigInt!
	closeFee: BigInt!
	updateTimestamp: BigInt!
	timestamp: BigInt!
}

type WeeklyHistory @entity(immutable: false) {
	id: ID!
	source: Bytes!
	tradeVolume: BigInt!
	activeUsers: BigInt!
	accountSource: Bytes
	timestamp: BigInt!
}

type MonthlyHistory @entity(immutable: false) {
	id: ID!
	source: Bytes!
	tradeVolume: BigInt!
	activeUsers: BigInt!
	accountSource: Bytes
	timestamp: BigInt!
}

type TotalHistory @entity(immutable: false) {
	id: ID!
	source: Bytes!
	quotesCount: BigInt!
	tradeVolume: BigInt!
	openTradeVolume: BigInt!
	closeTradeVolume: BigInt!
	liquidateTradeVolume: BigInt!
	deposit: BigInt!
	withdraw: BigInt!
	allocate: BigInt!
	deallocate: BigInt!
	users: BigInt!
	accounts: BigInt!
	platformFee: BigInt!
	openFee: BigInt!
	closeFee: BigInt!
	fundingPaid: BigInt!
	fundingReceived: BigInt!
	accountSource: Bytes
	collateral: Bytes!
	updateTimestamp: BigInt!
	timestamp: BigInt!
}

type TotalSolverHistory @entity(immutable: false) {
	id: ID!
	source: Bytes!
	tradeVolume: BigInt!
	openTradeVolume: BigInt!
	closeTradeVolume: BigInt!
	liquidateTradeVolume: BigInt!
	openInterest: BigInt!
	averagePositionSize: BigInt!
	positionsCount: BigInt!
	fundingPaid: BigInt!
	fundingReceived: BigInt!
	solver: Bytes!
	accountSource: Bytes
	updateTimestamp: BigInt!
	timestamp: BigInt!
}

type DailyUserHistory @entity(immutable: false) {
	id: ID!
	day: BigInt!
	user: Bytes!
	account: Bytes!
	quotesCount: BigInt!
	openTradeVolume: BigInt!
	closeTradeVolume: BigInt!
	liquidateTradeVolume: BigInt!
	deposit: BigInt!
	withdraw: BigInt!
	allocate: BigInt!
	deallocate: BigInt!
	accAllocate: BigInt!
	accDeallocate: BigInt!
	platformFeePaid: BigInt!
	openFeePaid: BigInt!
	closeFeePaid: BigInt!
	fundingPaid: BigInt!
	fundingReceived: BigInt!
	loss: BigInt!
	profit: BigInt!
	cvaPaid: BigInt!
	lfPaid: BigInt!
	accountSource: Bytes
	updateTimestamp: BigInt!
	timestamp: BigInt!
}

type TotalUserHistory @entity(immutable: false) {
	id: ID!
	account: Bytes!
	quotesCount: BigInt!
	openTradeVolume: BigInt!
	closeTradeVolume: BigInt!
	liquidateTradeVolume: BigInt!
	deposit: BigInt!
	withdraw: BigInt!
	allocate: BigInt!
	deallocate: BigInt!
	platformFeePaid: BigInt!
	openFeePaid: BigInt!
	closeFeePaid: BigInt!
	fundingPaid: BigInt!
	fundingReceived: BigInt!
	loss: BigInt!
	profit: BigInt!
	accountSource: Bytes
	updateTimestamp: BigInt!
	timestamp: BigInt!
}

type SymbolTradeHistory @entity(immutable: false) {
	id: ID!
	source: Bytes!
	symbolId: BigInt!
	timestamp: BigInt!
	updateTimestamp: BigInt!
	volume: BigInt!
	accountSource: Bytes
}

type DailySymbolTradesHistory @entity(immutable: false) {
	id: ID! # date + source + account_source + account + symbolId
	source: Bytes!
	day: BigInt!
	updateTimestamp: BigInt!
	account: Bytes!
	accountSource: Bytes
	symbolId: BigInt!
	totalTrades: BigInt!
	fundingReceived: BigInt!
	fundingPaid: BigInt!
	platformFeePaid: BigInt!
	openFeePaid: BigInt!
	closeFeePaid: BigInt!
	volume: BigInt!
}

type TotalSymbolTradesHistory @entity(immutable: false) {
	id: ID! # source + account_source + account + symbolId
	source: Bytes!
	updateTimestamp: BigInt!
	account: Bytes!
	accountSource: Bytes
	symbolId: BigInt!
	totalTrades: BigInt!
	fundingReceived: BigInt!
	fundingPaid: BigInt!
	platformFeePaid: BigInt!
	openFeePaid: BigInt!
	closeFeePaid: BigInt!
	volume: BigInt!
}

type OpenInterest @entity(immutable: false) {
	id: ID!
	amount: BigInt!
	weightedAmount: BigInt!
	timestamp: BigInt!
}

type Configuration @entity(immutable: false) {
	id: ID!
	collateral: Bytes!
	updateTimestamp: BigInt!
	updateTransaction: Bytes!
}

type GrantedRole @entity(immutable: false) {
	id: ID!
	role: String!
	user: Bytes!
	contract: Bytes
	grantTransaction: Bytes
	revokeTransaction: Bytes
	updateTimestamp: BigInt!
}

type OpenInterestSettleDay @entity(immutable: false) {
	id: ID!
	dayNumber: BigInt!
	timestamp: BigInt!
}

type FundingRateSnapshot @entity(immutable: true) {
	id: ID!
	source: Bytes!
	symbolId: BigInt!
	partyB: Bytes!
	longFee: BigInt
	shortFee: BigInt
	marketPrice: BigInt!
	eventType: String!
	timestamp: BigInt!
	blockNumber: BigInt!
	transaction: Bytes!
}

type FundingFeeState @entity(immutable: false) {
	id: ID!
	source: Bytes!
	symbolId: BigInt!
	symbolName: String!
	partyB: Bytes!
	currentLongRate: BigInt
	currentShortRate: BigInt
	accumulatedLongRate: BigInt
	accumulatedShortRate: BigInt
	epochDuration: BigInt
	lastUpdatedEpoch: BigInt
	startEpoch: BigInt
	startEpochTimestamp: BigInt
	lastUpdatedTimestamp: BigInt
	snapshotLongFee: BigInt
	snapshotShortFee: BigInt
	lastMarketPrice: BigInt
	updateTimestamp: BigInt!
}

type LiquidationDetail @entity(immutable: false) {
	id: ID!
	source: Bytes!
	partyA: Bytes!
	liquidationId: Bytes!
	liquidationType: Int!
	upnl: BigInt!
	totalUnrealizedLoss: BigInt!
	deficit: BigInt!
	liquidationFee: BigInt!
	timestamp: BigInt
	involvedPartyBCounts: BigInt!
	partyAAccumulatedUpnl: BigInt!
	disputed: Boolean!
	liquidationTimestamp: BigInt!
	liquidator: Bytes
	allocatedBalance: BigInt
	settled: Boolean!
	fullyLiquidated: Boolean!
	settledAmounts: [BigInt!]
	settledPartyBs: [Bytes!]
	affiliate: Bytes
	totalPnl: BigInt
	paidCva: BigInt
	paidLf: BigInt
	fullyLiquidatedTimestamp: BigInt
}

type WithdrawRequest @entity(immutable: false) {
	id: ID!
	source: Bytes!
	requestId: BigInt!
	user: Bytes!
	amount: BigInt!
	speedUp: Boolean!
	cooldownEndTime: BigInt!
	status: String!
	timestamp: BigInt!
	updateTimestamp: BigInt!
	blockNumber: BigInt!
	transaction: Bytes!
}

type LatestAccountBalance @entity(immutable: false) {
	id: ID!
	source: Bytes!
	account: Bytes!
	counterParty: Bytes
	accountType: String!
	allocatedBalance: BigInt!
	lockedCva: BigInt!
	lockedLf: BigInt!
	lockedPartyAmm: BigInt!
	lockedPartyBmm: BigInt!
	pendingLockedCva: BigInt!
	pendingLockedLf: BigInt!
	pendingLockedPartyAmm: BigInt!
	pendingLockedPartyBmm: BigInt!
	timestamp: BigInt!
	blockNumber: BigInt!
	transaction: Bytes!
}

type AggregatedPosition @entity(immutable: false) {
	id: ID!
	source: Bytes!
	partyA: Bytes!
	partyB: Bytes!
	symbolId: BigInt!
	symbolName: String!
	positionType: Int!
	aggregatedAmount: BigInt!
	aggregatedNotional: BigInt!
	weightedPaidFunding: BigInt!
	openPositionsCount: Int!
	isActive: Boolean!
	closedTimestamp: BigInt
	closedBlockNumber: BigInt
	closedTransaction: Bytes
	timestamp: BigInt!
	blockNumber: BigInt!
	transaction: Bytes!
}
