type Account @entity(immutable: false) {
	id: ID!
	source: Bytes
	deploymentId: String
	coreSource: Bytes
	accountLayerSource: Bytes
	account: Bytes!
	accountKind: String
	globalCounter: BigInt!
	user: Bytes!
	userRef: User
	owner: Bytes
	timestamp: BigInt!
	blockNumber: BigInt!
	name: String
	type: String
	lastActivityTimestamp: BigInt!
	transaction: Bytes!
	updateTimestamp: BigInt!
	accountSource: Bytes
	affiliateRef: Affiliate
	quotesCount: BigInt!
	positionsCount: BigInt!
	deposit: BigInt!
	withdraw: BigInt!
	allocated: BigInt!
	deallocated: BigInt!
	parentAddress: Bytes
	isVirtual: Boolean
	affiliate: Bytes
	subAccount: SubAccount
	virtualAccount: VirtualAccount
	lastCoreActivityTimestamp: BigInt
	lastLayerActivityTimestamp: BigInt
	lastBalanceActivityTimestamp: BigInt
	isDeleted: Boolean
}
