type AcceptCancelCloseRequest @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	closeId: BigInt!
	quoteId: BigInt!
	accountSource: Bytes!
	quoteStatus: Int!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type AcceptCancelRequest @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	quoteId: BigInt!
	accountSource: Bytes!
	quoteStatus: Int!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type ActiveEmergencyMode @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type AddBridge @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	bridge: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type AddSymbol @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	fundingRateEpochDuration: BigInt!
	fundingRateWindowTime: BigInt!
	maxLeverage: BigInt!
	minAcceptablePortionLF: BigInt!
	minAcceptableQuoteValue: BigInt!
	name: String!
	symbolId: BigInt!
	tradingFee: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type AllocateForPartyB @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	amount: BigInt!
	newAllocatedBalance: BigInt!
	partyA: Bytes!
	partyB: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type AllocatePartyA @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	amount: BigInt!
	newAllocatedBalance: BigInt!
	user: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type AllocatePartyB @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	amount: BigInt!
	partyA: Bytes!
	partyB: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type BalanceChangePartyA @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	_type: Int!
	amount: BigInt!
	partyA: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type BalanceChangePartyB @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	_type: Int!
	amount: BigInt!
	partyA: Bytes!
	partyB: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type ChargeFundingRate @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	partyA: Bytes!
	partyB: Bytes!
	quoteIds: [BigInt!]
	amounts: [BigInt!]
	rates: [BigInt!]
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type DeactiveEmergencyMode @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type DeallocateForPartyB @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	amount: BigInt!
	newAllocatedBalance: BigInt!
	partyA: Bytes!
	partyB: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type DeallocatePartyA @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	amount: BigInt!
	newAllocatedBalance: BigInt!
	user: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type DeferredLiquidatePartyA @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	allocatedBalance: BigInt!
	liquidationAllocatedBalance: BigInt!
	liquidationBlockNumber: BigInt!
	liquidationId: Bytes!
	liquidationTimestamp: BigInt!
	liquidator: Bytes!
	partyA: Bytes!
	totalUnrealizedLoss: BigInt!
	upnl: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type Deposit @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	amount: BigInt!
	sender: Bytes!
	user: Bytes!
	isVirtual: Boolean
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type DepositToReserveVault @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	amount: BigInt!
	partyB: Bytes!
	sender: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type DeregisterAffiliate @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	affiliate: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type DeregisterPartyB @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	index: BigInt!
	partyB: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type DisputeForLiquidation @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	liquidationId: Bytes!
	liquidator: Bytes!
	partyA: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type EmergencyClosePosition @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	closeId: BigInt!
	closedPrice: BigInt!
	filledAmount: BigInt!
	partyA: Bytes!
	partyB: Bytes!
	quoteId: BigInt!
	accountSource: Bytes!
	quoteStatus: Int!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type ExpireQuote @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	quoteId: BigInt!
	accountSource: Bytes!
	quoteStatus: Int!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type ExpireQuoteClose @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	closeId: BigInt!
	quoteId: BigInt!
	accountSource: Bytes!
	quoteStatus: Int!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type ExpireQuoteOpen @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	quoteId: BigInt!
	accountSource: Bytes!
	quoteStatus: Int!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type FillCloseRequest @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	closeId: BigInt!
	closedPrice: BigInt!
	filledAmount: BigInt!
	partyA: Bytes!
	partyB: Bytes!
	quoteId: BigInt!
	accountSource: Bytes!
	quoteStatus: Int!
	lockedValuesCva: BigInt
	lockedValuesLf: BigInt
	lockedValuesPartyAmm: BigInt
	lockedValuesPartyBmm: BigInt
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type ForceCancelCloseRequest @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	closeId: BigInt!
	quoteId: BigInt!
	accountSource: Bytes!
	quoteStatus: Int!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type ForceCancelQuote @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	quoteId: BigInt!
	accountSource: Bytes!
	quoteStatus: Int!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type ForceClosePosition @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	closeId: BigInt!
	closedPrice: BigInt!
	filledAmount: BigInt!
	partyA: Bytes!
	partyB: Bytes!
	quoteId: BigInt!
	accountSource: Bytes!
	quoteStatus: Int!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type FullyLiquidatedPartyA @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	liquidationId: Bytes!
	partyA: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type FullyLiquidatedPartyB @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	partyA: Bytes!
	partyB: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type InternalTransfer @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	amount: BigInt!
	sender: Bytes!
	user: Bytes!
	userNewAllocatedBalance: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type LiquidatePartyA @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	allocatedBalance: BigInt!
	liquidationId: Bytes!
	liquidator: Bytes!
	partyA: Bytes!
	totalUnrealizedLoss: BigInt!
	upnl: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type LiquidatePartyB @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	liquidator: Bytes!
	partyA: Bytes!
	partyB: Bytes!
	partyBAllocatedBalance: BigInt!
	upnl: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type LiquidatePendingPositionsPartyA @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	liquidatedAmounts: [BigInt!]
	liquidationId: Bytes!
	liquidator: Bytes!
	partyA: Bytes!
	quoteIds: [BigInt!]
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type LiquidatePositionsPartyA @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	closeIds: [BigInt!]
	liquidatedAmounts: [BigInt!]
	liquidationId: Bytes!
	liquidator: Bytes!
	partyA: Bytes!
	quoteIds: [BigInt!]
	averageClosedPrices: [BigInt!]
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type LiquidatePositionsPartyB @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	closeIds: [BigInt!]
	liquidatedAmounts: [BigInt!]
	liquidator: Bytes!
	partyA: Bytes!
	partyB: Bytes!
	quoteIds: [BigInt!]
	averageClosedPrices: [BigInt!]
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type LiquidationDisputed @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	liquidationId: Bytes!
	partyA: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type LockQuote @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	partyB: Bytes!
	quoteId: BigInt!
	accountSource: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type OpenPosition @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	filledAmount: BigInt!
	openedPrice: BigInt!
	partyA: Bytes!
	partyB: Bytes!
	quoteId: BigInt!
	accountSource: Bytes!
	lockedValuesCva: BigInt
	lockedValuesLf: BigInt
	lockedValuesPartyAmm: BigInt
	lockedValuesPartyBmm: BigInt
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type PauseAccounting @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type PauseGlobal @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type PauseInternalTransfer @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type PauseLiquidation @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type PausePartyAActions @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type PausePartyBActions @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type RegisterAffiliate @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	affiliate: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type RegisterPartyB @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	partyB: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type RemoveBridge @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	bridge: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type RequestToCancelCloseRequest @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	closeId: BigInt!
	partyA: Bytes!
	partyB: Bytes!
	quoteId: BigInt!
	accountSource: Bytes!
	quoteStatus: Int!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type RequestToCancelQuote @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	partyA: Bytes!
	partyB: Bytes!
	quoteId: BigInt!
	accountSource: Bytes!
	quoteStatus: Int!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type RequestToClosePosition @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	closeId: BigInt!
	closePrice: BigInt!
	deadline: BigInt!
	orderType: Int!
	partyA: Bytes!
	partyB: Bytes!
	quantityToClose: BigInt!
	quoteId: BigInt!
	accountSource: Bytes!
	quoteStatus: Int!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type ResolveLiquidationDispute @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	amounts: [BigInt!]
	disputed: Boolean!
	liquidationId: Bytes!
	partyA: Bytes!
	partyBs: [Bytes!]
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type RestoreBridgeTransaction @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	transactionId: BigInt!
	validAmount: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type RoleGranted @entity(immutable: true) {
	id: ID!
	source: Bytes
	counterId: BigInt!
	role: Bytes!
	user: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type RoleRevoked @entity(immutable: true) {
	id: ID!
	source: Bytes
	counterId: BigInt!
	role: Bytes!
	user: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SendQuote @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	cva: BigInt!
	deadline: BigInt!
	lf: BigInt!
	marketPrice: BigInt!
	orderType: Int!
	partyA: Bytes!
	partyAmm: BigInt!
	partyBmm: BigInt!
	partyBsWhiteList: [Bytes!]
	positionType: Int!
	price: BigInt!
	quantity: BigInt!
	quoteId: BigInt!
	accountSource: Bytes!
	symbolId: BigInt!
	tradingFee: BigInt!
	affiliate: Bytes
	data: Bytes
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetBalanceLimitPerUser @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	balanceLimitPerUser: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetCollateral @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	collateral: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetDeallocateCooldown @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	newDeallocateCooldown: BigInt!
	oldDeallocateCooldown: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetDeallocateDebounceTime @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	newDeallocateDebounceTime: BigInt!
	oldDeallocateDebounceTime: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetDefaultFeeCollector @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	newDefaultFeeCollector: Bytes!
	oldDefaultFeeCollector: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetFeeCollector @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	affiliate: Bytes!
	newFeeCollector: Bytes!
	oldFeeCollector: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetForceCancelCloseCooldown @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	newForceCancelCloseCooldown: BigInt!
	oldForceCancelCloseCooldown: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetForceCancelCooldown @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	newForceCancelCooldown: BigInt!
	oldForceCancelCooldown: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetForceCloseCooldown @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	newForceCloseCooldown: BigInt!
	oldForceCloseCooldown: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetForceCloseCooldowns @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	newForceCloseFirstCooldown: BigInt!
	newForceCloseSecondCooldown: BigInt!
	oldForceCloseFirstCooldown: BigInt!
	oldForceCloseSecondCooldown: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetForceCloseGapRatio @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	newForceCloseGapRatio: BigInt!
	oldForceCloseGapRatio: BigInt!
	symbolId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetForceCloseMinSigPeriod @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	newCloseMinSigPeriod: BigInt!
	oldCloseMinSigPeriod: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetForceClosePricePenalty @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	newPricePenalty: BigInt!
	oldPricePenalty: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetInvalidBridgedAmountsPool @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	newInvalidBridgedAmountsPool: Bytes!
	oldInvalidBridgedAmountsPool: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetLiquidationTimeout @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	newLiquidationTimeout: BigInt!
	oldLiquidationTimeout: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetLiquidatorShare @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	newLiquidatorShare: BigInt!
	oldLiquidatorShare: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetMuonConfig @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	priceValidTime: BigInt!
	upnlValidTime: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetMuonIds @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	gateway: Bytes
	muonAppId: BigInt!
	parity: Int
	x: BigInt
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetPartyBEmergencyStatus @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	partyB: Bytes!
	status: Boolean!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetPendingQuotesValidLength @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	newPendingQuotesValidLength: BigInt!
	oldPendingQuotesValidLength: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetSettlementCooldown @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	newSettlementCooldown: BigInt!
	oldSettlementCooldown: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetSuspendedAddress @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	isSuspended: Boolean!
	user: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetSymbolAcceptableValues @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	minAcceptablePortionLF: BigInt!
	minAcceptableQuoteValue: BigInt!
	oldMinAcceptablePortionLF: BigInt!
	oldMinAcceptableQuoteValue: BigInt!
	symbolId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetSymbolFundingState @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	fundingRateEpochDuration: BigInt!
	fundingRateWindowTime: BigInt!
	symbolId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetSymbolMaxLeverage @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	maxLeverage: BigInt!
	oldMaxLeverage: BigInt!
	symbolId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetSymbolMaxSlippage @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	maxSlippage: BigInt!
	oldMaxSlippage: BigInt!
	symbolId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetSymbolTradingFee @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	oldTradingFee: BigInt!
	symbolId: BigInt!
	tradingFee: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetSymbolsPrices @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	liquidationId: Bytes!
	liquidator: Bytes!
	partyA: Bytes!
	prices: [BigInt!]
	symbolIds: [BigInt!]
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetSymbolValidationState @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	isValid: Boolean!
	oldState: Boolean!
	symbolId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SettlePartyALiquidation @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	amounts: [BigInt!]
	liquidationId: Bytes!
	partyA: Bytes!
	partyBs: [Bytes!]
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type QuoteSettlementData @entity(immutable: true) {
	id: ID!
	quoteId: BigInt!
	accountSource: Bytes!
	currentPrice: BigInt!
	partyBUpnlIndex: Int!
}

type SettleUpnl @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	newPartyAAllocatedBalance: BigInt!
	newPartyBsAllocatedBalances: [BigInt!]
	partyA: Bytes!
	settlementData: [QuoteSettlementData!]
	updatedPrices: [BigInt!]
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SuspendBridgeTransaction @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	transactionId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type TransferAllocation @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	amount: BigInt!
	origin: Bytes!
	originNewAllocatedBalance: BigInt!
	recipient: Bytes!
	recipientNewAllocatedBalance: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type TransferToBridge @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	amount: BigInt!
	bridgeAddress: Bytes!
	transactionId: BigInt!
	user: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type UnlockQuote @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	partyB: Bytes!
	quoteId: BigInt!
	accountSource: Bytes!
	quoteStatus: Int!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type UnpauseAccounting @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type UnpauseGlobal @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type UnpauseInternalTransfer @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type UnpauseLiquidation @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type UnpausePartyAActions @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type UnpausePartyBActions @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type Withdraw @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	amount: BigInt!
	sender: Bytes!
	user: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type WithdrawFromReserveVault @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	amount: BigInt!
	partyB: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type WithdrawReceivedBridgeValue @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	transactionId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type WithdrawReceivedBridgeValues @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	transactionIds: [BigInt!]
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type AddAccount @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	account: Bytes!
	user: Bytes!
	accountSource: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SymmioStakeholderUpdated @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	oldReceiver: Bytes!
	newReceiver: Bytes!
	oldShare: BigInt!
	newShare: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type DiamondCut @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type UnifiedQuoteSettlementData @entity(immutable: true) {
	id: ID!
	quoteId: BigInt!
	currentPrice: BigInt!
	partyAIndex: Int!
}

type WithdrawPart @entity(immutable: true) {
	id: ID!
	partId: BigInt!
	amount: BigInt!
	chainId: BigInt!
	receiver: Bytes!
	virtualProvider: Bytes!
	expressProvider: Bytes!
}

type ADLClose @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	quoteId: BigInt!
	amount: BigInt!
	price: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type AcceptVirtualExternalTransfer @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	transferId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type AccumulatedFundingActivated @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type ActivateCrossPartyB @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	user: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type ActivateInstantActionMode @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	partyA: Bytes!
	time: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type AddRelayerForExternalTransferTarget @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	target: Bytes!
	relayer: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type AutoTakeoverPartyALiquidation @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	partyA: Bytes!
	liquidationId: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type BindToPartyB @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	partyA: Bytes!
	partyB: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type BlacklistSymbols @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	partyB: Bytes!
	symbolId: [BigInt!]!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type CancelUnbindRequest @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	partyA: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type CancelVirtualExternalTransfer @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	transferId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type ChargeAccumulatedFundingFee @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	partyA: Bytes!
	partyB: Bytes!
	quoteIds: [BigInt!]!
	sender: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type CompleteUnbindRequest @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	partyA: Bytes!
	partyB: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type CrossLockedValuesMigrated @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	partyB: Bytes!
	partyAsProcessed: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type DeactivateInstantActionMode @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	partyA: Bytes!
	time: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type DeallocateForClearingHouse @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	subject: Bytes!
	parties: [Bytes!]!
	allocationKeys: [Bytes!]!
	amounts: [BigInt!]!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type DeallocateSuspendedUser @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	admin: Bytes!
	user: Bytes!
	amount: BigInt!
	newAllocatedBalance: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type DepositVirtualFunds @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	provider: Bytes!
	amount: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type DistributeForClearingHouse @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	subject: Bytes!
	receivers: [Bytes!]!
	allocationKeys: [Bytes!]!
	amounts: [BigInt!]!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type ExternalTransfer @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	sender: Bytes!
	receiver: Bytes!
	amount: BigInt!
	target: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type ForceCloseInitialized @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	initiator: Bytes!
	partyB: Bytes!
	quoteId: BigInt!
	highLowPriceSigId: Bytes!
	closePrice: BigInt!
	timestamp: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type ForceClosePartyBInsolvent @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	quoteId: BigInt!
	partyA: Bytes!
	partyB: Bytes!
	closedPrice: BigInt!
	currentPrice: BigInt!
	upnlPartyB: BigInt!
	partyBAvailableAfterClose: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type ForceFetchAllocated @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	partyB: Bytes!
	partyAs: [Bytes!]!
	FetchedAmount: [BigInt!]!
	newPartyBsAllocatedBalances: [BigInt!]!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type InitiateVirtualExternalTransfer @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	transferId: BigInt!
	sender: Bytes!
	receiver: Bytes!
	amount: BigInt!
	target: Bytes!
	provider: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type InternalTransferToBalance @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	sender: Bytes!
	user: Bytes!
	userNewBalance: BigInt!
	amount: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type LegacyFundingDeprecated @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type LegacyWithdrawalDeprecated @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type LiquidateCrossPartyB @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	initiator: Bytes!
	partyB: Bytes!
	liquidationId: Bytes!
	upnl: BigInt!
	timestamp: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type LiquidatePendingPositionsForClearingHouse @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	subject: Bytes!
	counterparties: [Bytes!]!
	liquidatedAmounts: [BigInt!]!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type LiquidatePositionsForClearingHouse @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	subject: Bytes!
	quoteIds: [BigInt!]!
	liquidatedAmounts: [BigInt!]!
	closeIds: [BigInt!]!
	prices: [BigInt!]!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type PauseExternalTransfer @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type PauseInstantLayer @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type PausePartyBOpenPositions @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type PledgeCollateralDeposited @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	user: Bytes!
	token: Bytes!
	amount: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type PledgeWithdrawApproved @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	user: Bytes!
	token: Bytes!
	amount: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type PledgeWithdrawCancelled @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	user: Bytes!
	token: Bytes!
	amount: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type PledgeWithdrawRequested @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	user: Bytes!
	token: Bytes!
	amount: BigInt!
	recipient: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type ProposeToDeactivateInstantActionMode @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	partyA: Bytes!
	time: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type QuotesMigrated @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	quotesProvided: BigInt!
	quotesMigrated: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type RegisterExpressProvider @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	provider: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type RegisterHook @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	affiliate: Bytes!
	hook: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type RegisterVirtualProvider @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	provider: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type RemoveRelayerForExternalTransferTarget @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	target: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type RemoveSymbolTypeFromWhitelist @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	partyB: Bytes!
	symbolType: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type RemoveSymbolsFromBlacklist @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	partyB: Bytes!
	symbolId: [BigInt!]!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type RemoveSymbolsFromWhitelist @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	partyB: Bytes!
	symbolIds: [BigInt!]!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type RequestToUnbindFromPartyB @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	partyA: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type RoleAdminAdded @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	role: Bytes!
	admin: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type RoleAdminRemoved @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	role: Bytes!
	admin: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetADLEnabled @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	partyB: Bytes!
	enabled: Boolean!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetAffiliateFee @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	affiliate: Bytes!
	symbolId: BigInt!
	oldOpenFee: BigInt!
	newOpenFee: BigInt!
	oldCloseFee: BigInt!
	newCloseFee: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetAffiliateFeeForUser @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	affiliate: Bytes!
	user: Bytes!
	symbolId: BigInt!
	oldOpenFee: BigInt!
	newOpenFee: BigInt!
	oldCloseFee: BigInt!
	newCloseFee: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetCrossPartyB @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	partyB: Bytes!
	enabled: Boolean!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetCrossPartyBModeActivated @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	oldValue: Boolean!
	newValue: Boolean!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetEntityMetadata @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	entity_: Bytes!
	name: String!
	brandColor: String!
	metadata: String!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetEpochDuration @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	symbolIds: [BigInt!]!
	durations: [BigInt!]!
	partyB: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetLegacyDeallocateDeprecated @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	oldValue: Boolean!
	newValue: Boolean!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetLiquidationInsuranceVaultParams @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	insuranceVault: Bytes!
	maxLiquidationProfit: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetLongFundingFee @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	symbolIds: [BigInt!]!
	fees: [BigInt!]!
	marketPrices: [BigInt!]!
	partyB: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetMaxPartyAConnectionLimit @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	maxLimit: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetMaxWithdrawParts @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	maxWithdrawParts: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetMinAffiliateFee @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	oldMinAffiliateFee: BigInt!
	newMinAffiliateFee: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetMinWithdrawCooldown @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	lastMinWithdrawCooldown: BigInt!
	newMinWithdrawCooldown: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetPartyBBindable @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	partyB: Bytes!
	bindable: Boolean!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetPureVirtualCancelBlackout @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	oldBlackout: BigInt!
	newBlackout: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetShortFundingFee @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	symbolIds: [BigInt!]!
	fees: [BigInt!]!
	marketPrices: [BigInt!]!
	partyB: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetSignatureVerifierAddress @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	SignatureVerifier: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetSoftLiquidationPenaltyCollector @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	softLiquidationPenaltyCollector: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetSpeedUpUser @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	user: Bytes!
	speedUp: Boolean!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetSymbolType @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	symbolIds: BigInt!
	symbolTypes: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetUnbindCooldown @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	oldUnbindCooldown: BigInt!
	newUnbindCooldown: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SetWithdrawCooldownPeriod @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	oldWithdrawCooldownPeriod: BigInt!
	newWithdrawCooldownPeriod: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SettleCrossPartyBLiquidation @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	partyB: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SettlePartyATakeover @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	partyA: Bytes!
	liquidationId: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SettleUpnlUnified @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	settlementId: Bytes!
	settlementData: [UnifiedQuoteSettlementData!]
	updatedPrices: [BigInt!]!
	partyB: Bytes!
	partyAs: [Bytes!]!
	newPartyAsAllocatedBalances: [BigInt!]!
	newPartyBAllocatedBalance: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SignerSet @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	signer: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type SoftPartyBLiquidation @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	partyB: Bytes!
	partyA: Bytes!
	penaltyFromAllocated: BigInt!
	penaltyFromBalance: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type TakeoverPartyALiquidation @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	partyA: Bytes!
	liquidationId: Bytes!
	timestamp: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type TradeVolumeRecorded @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	quoteId: BigInt!
	amount: BigInt!
	partyA: Bytes!
	partyB: Bytes!
	symbolId: BigInt!
	affiliate: Bytes!
	_type: Int!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type TradingFeeCharged @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	quoteId: BigInt!
	amount: BigInt!
	partyA: Bytes!
	partyB: Bytes!
	symbolId: BigInt!
	affiliate: Bytes!
	_type: Int!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type UnpauseExternalTransfer @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type UnpauseInstantLayer @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type UnpausePartyBOpenPositions @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type UnregisterExpressProvider @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	provider: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type UnregisterVirtualProvider @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	provider: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type UpdateAccumulatedFundingFee @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	symbolIds: [BigInt!]!
	longRates: [BigInt!]!
	shortRates: [BigInt!]!
	marketPrices: [BigInt!]!
	partyB: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type UserSlashed @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	user: Bytes!
	token: Bytes!
	amount: BigInt!
	recipient: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type WhitelistSymbolType @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	partyB: Bytes!
	symbolType: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type WhitelistSymbols @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	partyB: Bytes!
	symbolIds: [BigInt!]!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type WithdrawAccepted @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	requestId: BigInt!
	user: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type WithdrawCancelRequested @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	requestId: BigInt!
	user: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type WithdrawCancelled @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	requestId: BigInt!
	user: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type WithdrawFinalized @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	requestId: BigInt!
	user: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type WithdrawInitiated @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	requestId: BigInt!
	user: Bytes!
	parts: [WithdrawPart!]
	speedUp: Boolean!
	providerData: Bytes!
	cooldownEndTime: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type WithdrawRejected @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	requestId: BigInt!
	user: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type WithdrawSpeedUpAccepted @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	requestId: BigInt!
	user: Bytes!
	newCooldown: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type WithdrawSuspended @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	requestId: BigInt!
	user: Bytes!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}

type WithdrawSuspendedUser @entity(immutable: true) {
	id: ID!
	source: Bytes!
	counterId: BigInt!
	admin: Bytes!
	user: Bytes!
	recipient: Bytes!
	amount: BigInt!
	blockNumber: BigInt!
	blockTimestamp: BigInt!
	transactionHash: Bytes!
	transactionIndex: BigInt!
	logIndex: BigInt!
	blockHash: Bytes!
}
